version: '3'
services:
  frontend:
    image: frontend
    ports:
      - 5000:5000
  backend:
    image: backend
    environment:
      - GIN_MODE=release
      - REDIS_HOST=redis
      - POSTGRES_HOST=db
      - POSTGRES_USER=superuser
      - POSTGRES_PASSWORD=imSoSuper9000
    ports:
      - 8080:8080
  redis:
    image: redis
    restart: always
  db:
    image: postgres:13.2-alpine
    restart: unless-stopped
    environment:
      POSTGRES_USER: superuser
      POSTGRES_PASSWORD: imSoSuper9000
    container_name: database