version: '3.8'
services:
  nginx:
    image: nginx:stable
    restart: always
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - 80:80
  frontend:
    image: frontend
    restart: always
  backend:
    image: backend
    environment:
      - GIN_MODE=release
      - REDIS_HOST=redis
      - POSTGRES_HOST=db
      - POSTGRES_USER=superuser
      - POSTGRES_PASSWORD=imSoSuper9000
  redis:
    image: redis
    restart: always
    volumes:
      - ./database:/data
  db:
    image: postgres:13.2-alpine
    restart: unless-stopped
    volumes:
      - ./database:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: superuser
      POSTGRES_PASSWORD: imSoSuper9000
    container_name: database